#!/bin/bash

OUTFILE=../res.h

cd resource;

cat > $OUTFILE << EOF
/*
	This file is automatically generated during the build by base64 encoding
	all of the files in the resource directory.
*/

#include <unordered_map>

std::unordered_map<std::string, std::string> resources;

void loadResources(){
EOF

for F in *; do
	cat >> $OUTFILE <<-EOF
		resources["$F"] = $(base64 "$F" | sed -e 's/\(^.*$\)/"\1"/');
	EOF
done

cat >> $OUTFILE << EOF
}
EOF
