#!/bin/bash

OUTFILE=../res.h

cd resource;

cat > $OUTFILE << EOF
/*
	This file is automatically generated during the build by base64 encoding
	all of the files in the resource directory.
*/

#include <unordered_map>

struct Resource {
	std::string mime, data;
};

std::ostream& operator << (std::ostream &os, Resource const& rsc){
	os << rsc.data;
	return os;
}

std::unordered_map<std::string, Resource> resources;

void loadResources(){
EOF

for F in *; do
	cat >> $OUTFILE <<-EOF
		resources["$F"] = {
			.mime = "$(mimetype -b "$F")",
			.data = $(base64 "$F" | sed -e 's/\(^.*$\)/"\1"/')
		};
	EOF
done

cat >> $OUTFILE << EOF
}
EOF
